name: Rails CI

on:
    push:
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs_on: ubuntu-latest

        services: 
            postgres:
                image: postgres:13
                ports: ['5432:5432']
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: password
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
        - user: actions/checkout@v4
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
                ruby-version: '2.7.6'
        
        - name: install dependencies
          run: |
                gem install bundler -v 2.2.33
                bundle install
        
        - name: Set up database
          run: |
                cp config/database.yml.github config/database.yml
                bundle exec rake db:create db:migrate
        
        - name: Run tests
         run: |
                bundle exec rails rspec